Repository woowa-techcamp-2022/android-repo-09, pull requests merged in 2022-07, with the labels that each got.

#9 [FEATURE] Main 화면 디자인 작업
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/MainViewModel.kt
  app/src/main/res/color/color_text_selector_main_tab.xml
  app/src/main/res/drawable/bg_main.xml
  app/src/main/res/drawable/btn_main_tab_selector.xml
  app/src/main/res/drawable/ic_person_circle.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_pressed.xml
  app/src/main/res/drawable/ic_selector_search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature 🚀, 웅재 🦊

#14 [FEATURE] Sign In 화면 임시 코드 제거 및 기능, 디자인 구현
  app/src/main/java/co/kr/woowahan_repo/application/AppContainer.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/repositoryimpl/GithubIssuesRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/repositoryimpl/GithubOAuthRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssuesResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/OAuthAccessTokenResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/service/GithubIssuesService.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubIssueModel.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/OAuthAccessTokenInfo.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubIssuesRepository.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubOAuthRepository.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesDiffUtilCallback.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/signin/SignInActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/IssuesViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
  app/src/main/res/color/color_text_selector_sign_in.xml
  app/src/main/res/drawable/btn_sign_in_selector.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design 🎨, feature 🚀, 웅재 🦊

#12 [FEATURE] Main Activity 의 탭에 두개의 Fragment를 연결, Issues Fragment에 Api 연동 확인
  app/src/main/java/co/kr/woowahan_repo/application/AppContainer.kt
  app/src/main/java/co/kr/woowahan_repo/application/util/AppCompatActivityExtension.kt
  app/src/main/java/co/kr/woowahan_repo/application/util/FragmentExtension.kt
  app/src/main/java/co/kr/woowahan_repo/data/SingleEvent.kt
  app/src/main/java/co/kr/woowahan_repo/data/api/ServiceCreator.kt
  app/src/main/java/co/kr/woowahan_repo/data/service/GithubIssuesService.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/NotificationsFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/MainViewModel.kt
  app/src/main/res/drawable/bg_main_header.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_issues.xml
  app/src/main/res/layout/fragment_notifications.xml
Labels: feature 🚀, 웅재 🦊

#16 [FEATURE] Notifications 서버 통신 관련 domain layer 구현
  app/src/main/java/co/kr/woowahan_repo/application/AppContainer.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssuesResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubNotificationResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubIssuesRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubOAuthRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/NotificationsRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/service/NotificationsService.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubIssueModel.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubNotification.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/NotificationsRepository.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/NotificationsViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/util/AppCompatActivityExtension.kt
  app/src/main/java/co/kr/woowahan_repo/util/DateUtil.kt
  app/src/main/java/co/kr/woowahan_repo/util/FragmentExtension.kt
Labels: feature 🚀, refactor 🛠, 승현 🛵

#20 [FEATURE] 검색 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_repo/application/util/PagingListener.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/repositoryimpl/GithubRepositorySearchRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/RepositorySearchResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/service/GithubRepositorySearchService.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubRepositorySearchModel.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubRepositorySearchRepository.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryDiffUtil.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_arrow_left_pressed.xml
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/drawable/ic_selector_arrow_left.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/activity_search_repository.xml
  app/src/main/res/layout/view_search_repository_item.xml
  app/src/main/res/values/strings.xml
Labels: feature 🚀, 웅재 🦊

#24 [FEATURE] Issues 화면 팝업 메뉴 디자인
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/view/PopupMenuChooseView.kt
  app/src/main/res/drawable/bg_popup_menu_issue_filter.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_check_pressed.xml
  app/src/main/res/drawable/ic_selector_check.xml
  app/src/main/res/drawable/ic_selector_menu_issue_filter.xml
  app/src/main/res/menu/menu_issue_state.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: design 🎨, feature 🚀, 웅재 🦊

#25 [REFACTOR] Issues Api 코드 리팩토링, 수정
  app/src/main/java/co/kr/woowahan_repo/application/AppContainer.kt
  app/src/main/java/co/kr/woowahan_repo/application/WoowahanRepoApplication.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssueResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssuesResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubIssuesRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/service/GithubIssuesService.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubIssueModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
Labels: refactor 🛠, 웅재 🦊

#27 [REFACTOR] Repository 객체의 의미에 맞게 Api 성공 실패에 대한 판별도 포함하도록 변경
  app/src/main/java/co/kr/woowahan_repo/data/model/repositoryimpl/GithubRepositorySearchRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubIssuesRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubOAuthRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubRepositorySearchRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/NotificationsRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubIssuesRepository.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubOAuthRepository.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubRepositorySearchRepository.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/NotificationsRepository.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/IssuesViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/NotificationsViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
Labels: refactor 🛠, 웅재 🦊

#29 [FIX] Issue Date 파싱 오류 해결
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssueResponse.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/util/DateUtil.kt
Labels: bug 🐛, 웅재 🦊

#30 [FEATURE] Main 화면에서 git profile api 호출하여 프로필 이미지 가져와 보여주기
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubProfileResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubProfileRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/service/GithubProfileService.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubProfileModel.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubProfileRepository.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/MainViewModel.kt
  app/src/main/res/drawable/ic_person_circle.xml
  app/src/main/res/layout/activity_main.xml
Labels: feature 🚀, 웅재 🦊

#31 [FEATURE] Search Api 쿼리 제한 확인 및 개선
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubSearchLimitResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/RepositorySearchResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubRepositorySearchRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/service/GithubSearchLimitService.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubRepositorySearchModel.kt
  app/src/main/java/co/kr/woowahan_repo/domain/repository/GithubRepositorySearchRepository.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
Labels: feature 🚀, 웅재 🦊

#33 [DESIGN] Main Design 적용
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/res/drawable/bg_main.xml
  app/src/main/res/drawable/btn_main_tab_selector.xml
Labels: design 🎨, 웅재 🦊

#34 [FEATURE] Notification 탭 UI 구현
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubNotificationResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/NotificationsRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubNotification.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/NotificationsFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/NotificationsViewModel.kt
  app/src/main/res/drawable/rectangle_radius_3.xml
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/layout/view_notification_item.xml
Labels: feature 🚀, 승현 🛵

#38 [FEATURE] 검색 아이템 뷰 - Repository 개발 언어에 따른 색상 구현
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/util/ColorUtil.kt
  app/src/main/res/layout/view_search_repository_item.xml
Labels: feature 🚀, 웅재 🦊

#40 [Design] 검색 화면 Motion Layout 적용
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/view/CollapsibleToolbar.kt
  app/src/main/res/layout/activity_search_repository.xml
  app/src/main/res/xml/motion_search_header.xml
Labels: design 🎨, 웅재 🦊

#42 [FEATURE] Github Profile 화면에 필요한 데이터 요청하도록 Api 수정
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubProfileResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubUserRepositoriesResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubProfileRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/service/GithubUsersRepositoriesService.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubProfileModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
Labels: feature 🚀, 웅재 🦊

#50 [FEATURE] 프로필 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubProfileResponse.kt
  app/src/main/java/co/kr/woowahan_repo/domain/model/GithubProfileModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationTouchHelper.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/profile/ProfileActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/signin/SignInActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/NotificationsViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/res/drawable/bg_bio.xml
  app/src/main/res/drawable/bg_profile_repository_star.xml
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_mail.xml
  app/src/main/res/drawable/ic_repository.xml
  app/src/main/res/drawable/ic_starred.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/layout/activity_profile.xml
Labels: feature 🚀, 승현 🛵

#47 [REFACTOR] Service Locator 패턴 리팩토링
  app/src/main/java/co/kr/woowahan_repo/application/WoowahanRepoApplication.kt
  app/src/main/java/co/kr/woowahan_repo/data/WoowahanSharedPreferences.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubCommentsRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubOAuthRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubRepositorySearchRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/GithubTokenDataSource.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/profile/ProfileActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/signin/SignInActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/IssuesViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/NotificationsViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/ViewModelFactory.kt
Labels: refactor 🛠, 웅재 🦊

#54 [REFACTOR] 세부적인 코드 스타일 리팩토링
  app/src/main/java/co/kr/woowahan_repo/data/api/interceptor/AuthInterceptor.kt
  app/src/main/java/co/kr/woowahan_repo/data/datasource/WoowahanSharedPreferences.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssueResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/OAuthAccessTokenResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/RepositorySearchResponse.kt
  app/src/main/java/co/kr/woowahan_repo/di/RepositoryModule.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceModule.kt
  app/src/main/java/co/kr/woowahan_repo/domain/GithubApiDateFormat.kt
  app/src/main/java/co/kr/woowahan_repo/domain/datasource/GithubTokenDataSource.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/profile/ProfileActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/signin/SignInActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/IssuesViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/util/DateUtil.kt
  app/src/main/res/layout/activity_profile.xml
Labels: refactor 🛠, 웅재 🦊

#55 [REFACTOR] Hilt Module 기능, 생명주기를 고려하여 분리
  app/src/main/java/co/kr/woowahan_repo/di/AppModule.kt
  app/src/main/java/co/kr/woowahan_repo/di/DataSourceModule.kt
  app/src/main/java/co/kr/woowahan_repo/di/RepositoryModule.kt
  app/src/main/java/co/kr/woowahan_repo/di/RetrofitModule.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceModule.kt
Labels: refactor 🛠, 웅재 🦊

#57 REFACTOR] Service-Locator 브랜치 세부적인 코드 리팩토링
  app/src/main/java/co/kr/woowahan_repo/application/WoowahanRepoApplication.kt
  app/src/main/java/co/kr/woowahan_repo/data/datasource/WoowahanSharedPreferences.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/GithubIssueResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/OAuthAccessTokenResponse.kt
  app/src/main/java/co/kr/woowahan_repo/data/model/response/RepositorySearchResponse.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/GithubApiDateFormat.kt
  app/src/main/java/co/kr/woowahan_repo/domain/datasource/GithubTokenDataSource.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/PagingListener.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/notifications/NotificationsFragment.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/profile/ProfileActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryAdapter.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/signin/SignInActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/IssuesViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/MainViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/ProfileViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SignInViewModel.kt
  app/src/main/java/co/kr/woowahan_repo/util/DateUtil.kt
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_search_repository.xml
Labels: refactor 🛠, 웅재 🦊

#59 [REFACTOR] Search Repository Activity progress 위치 조정, Paging Listener 패키지 이동
  app/src/main/java/co/kr/woowahan_repo/presentation/PagingListener.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/java/co/kr/woowahan_repo/util/DateUtil.kt
  app/src/main/res/layout/activity_search_repository.xml
Labels: refactor 🛠, 웅재 🦊

#62 [FIX] Issue 탭 문제 수정
  app/src/main/java/co/kr/woowahan_repo/data/service/GithubIssuesService.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/util/RecyclerViewExtension.kt
  app/src/main/res/layout/view_issue_item.xml
Labels: bug 🐛, 웅재 🦊

#63 [FIX] Date TimeZone 수정
  app/src/main/java/co/kr/woowahan_repo/domain/GithubApiDateFormat.kt
Labels: bug 🐛, 웅재 🦊

#65 [FIX] 프로필 이미지 캐시처리 누락된 코드 수정
  app/src/main/java/co/kr/woowahan_repo/data/datasource/WoowahanSharedPreferences.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubProfileRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/di/DataSourceModule.kt
  app/src/main/java/co/kr/woowahan_repo/domain/datasource/GithubProfileDataSource.kt
Labels: bug 🐛, 웅재 🦊

#67 [FEATURE] 검색 화면사용환경 개선을 위한 2가지 추가 기능
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
Labels: feature 🚀, 웅재 🦊

#69 [FIX] 이전 검색 요청 취소 발생시, progress visible 처리가 꼬이는 문제 수정
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
  app/src/main/res/layout/activity_search_repository.xml
Labels: bug 🐛, 웅재 🦊

#71 [FIX][Service-Locator] Issue 탭 문제 수정
  app/src/main/java/co/kr/woowahan_repo/data/service/GithubIssuesService.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/issues/IssuesFragment.kt
  app/src/main/java/co/kr/woowahan_repo/util/RecyclerViewExtension.kt
  app/src/main/res/layout/view_issue_item.xml
Labels: bug 🐛, 웅재 🦊

#73 [FIX][Service-Locator] Date TimeZone 수정
  app/src/main/java/co/kr/woowahan_repo/domain/GithubApiDateFormat.kt
Labels: bug 🐛, 웅재 🦊

#75 [FIX][Service-Locator] 프로필 이미지 캐시처리 누락된 코드 수정
  app/src/main/java/co/kr/woowahan_repo/data/datasource/GithubProfileDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_repo/data/repository/GithubProfileRepositoryImpl.kt
  app/src/main/java/co/kr/woowahan_repo/di/ServiceLocator.kt
  app/src/main/java/co/kr/woowahan_repo/domain/datasource/GithubProfileDataSource.kt
Labels: bug 🐛, 웅재 🦊

#77 [FEATURE][Service-Locator] 검색 화면사용환경 개선을 위한 2가지 추가 기능
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
Labels: bug 🐛, 웅재 🦊

#79 [FIX][Service-Locator] 이전 검색 요청 취소 발생시, progress visible 처리가 꼬이는 문제 수정
  app/src/main/java/co/kr/woowahan_repo/presentation/viewmodel/SearchRepositoryViewModel.kt
Labels: bug 🐛, 웅재 🦊

#81 [FIX] Search Activity Progress 가 모션레이아웃에 가려져서 안보이는 문제 수정
  app/src/main/java/co/kr/woowahan_repo/presentation/ui/search/SearchRepositoryActivity.kt
  app/src/main/res/layout/activity_search_repository.xml
Labels: bug 🐛, 웅재 🦊

#83 [FIX] 프로필 DataSource 구현체 변경
  app/src/main/java/co/kr/woowahan_repo/data/datasource/GithubProfileDataSourceImpl.kt
  app/src/main/java/co/kr/woowahan_repo/di/DataSourceModule.kt
Labels: bug 🐛, 웅재 🦊
